### ISSUE TITLE
Template cannot be legally used because of missing license

### ISSUE THREAD

**Issue by squah-confluent** [terraform-linters/tflint-ruleset-template#106]
As there is no license on this repo, default copyright laws apply and developers do not have the right to use the template.
The other tflint-ruleset-* repos are MPL 2.0 licensed. Could the same license be added here?

According to https://help.github.com/en/articles/licensing-a-repository:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

**Comment by wata727** [comment]
Thank you for raising this issue.

The template repository intentionally did not include license files, to allow you to choose your preferred license whenever possible. But as you say, the lack of a license may be unclear.

The reason why tflint-rulset-* choose the MPL 2.0 license is that many of HashiCorp's repositories are distributed under the MPL 2.0, which makes it convenient to pull code snippets when needed. If we add MPL 2.0 license, all ruleset developers must continue to distribute at least the original files under MPL 2.0.

With this in mind, there may be room for a non-copyleft license, but I wouldn't be opposed to adding MPL 2.0 license. What do you think?

**Comment by squah-confluent** [comment]
Thanks for the fast response. It sounds like MPL 2.0 isn't the right license for this repo if the intent is to allow developers to choose their own license. The [Zero-Clause BSD license](https://choosealicense.com/licenses/0bsd/) or [MIT No-Attribution license](https://choosealicense.com/licenses/mit-0/) look compatible with that intent. Both are very permissive and don't require reproduction of the license.

**Comment by wata727** [comment]
Thank you for your suggestion.
The Zero-Clause BSD license seems better, so I added it in #107.
